### ISSUE TITLE
`import_meta.url` is `undefined` in CJS bundle

### ISSUE THREAD

**Issue by frabarz** [egoist/bundle-require#37]
I just upgraded `tsup` to v6.6.0, which uses `bundle-require` v4.0.0, and now when trying to use the `tsup` command this error appears:
```
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, 
file URL string, or absolute path string. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at createRequire (node:internal/modules/cjs/loader:1224:11)
    at dynamicImport (C:\Users\...\node_modules\bundle-require\dist\index.cjs:75:154)
    at extractResult (C:\Users\...\node_modules\bundle-require\dist\index.cjs:190:21)
    at async run (C:\Users\...\node_modules\bundle-require\dist\index.cjs:228:17)
```
Following the line numbers, the error seems to be caused by passing an `undefined` value to `createRequire` [here](https://github.com/egoist/bundle-require/blob/main/src/utils.ts#L52). In the CJS bundle, usage of `import.meta` gets transformed into `var import_meta = {};`, and `import_meta.url` becomes `undefined`.

I'm running `tsup` in a monorepo, using node v16.16.0, on Windows 10.

**Comment by frabarz** [comment]
Fixed in v4.0.1
